import { StyleSheet } from '@react-pdf/renderer';

export const pdfStyles = {
  // 1. 모던 & 미니멀 스타일
  modern: StyleSheet.create({
    page: {
      fontFamily: 'Nanum Gothic',
      fontSize: 11,
      padding: 40,
      backgroundColor: '#FFFFFF',
    },
    header: {
      marginBottom: 30,
      paddingBottom: 20,
      borderBottom: '1px solid #E5E7EB',
    },
    title: {
      fontFamily: 'Nanum Gothic Bold',
      fontSize: 32,
      fontWeight: 'bold',
      marginBottom: 20,
      color: '#1F2937',
      letterSpacing: 2,
    },
    companyInfo: {
      fontSize: 10,
      marginBottom: 4,
      color: '#6B7280',
      lineHeight: 1.5,
    },
    section: {
      marginBottom: 25,
    },
    sectionTitle: {
      fontFamily: 'Nanum Gothic Bold',
      fontSize: 14,
      fontWeight: 'bold',
      marginBottom: 15,
      color: '#1F2937',
      paddingBottom: 8,
      borderBottom: '2px solid #3B82F6',
    },
    infoRow: {
      flexDirection: 'row',
      marginBottom: 8,
      paddingVertical: 4,
    },
    infoLabel: {
      width: 120,
      fontSize: 10,
      color: '#6B7280',
    },
    infoValue: {
      flex: 1,
      fontSize: 10,
      color: '#1F2937',
    },
    table: {
      marginTop: 10,
    },
    tableHeader: {
      flexDirection: 'row',
      backgroundColor: '#F3F4F6',
      borderRadius: 4,
      padding: 12,
      marginBottom: 4,
    },
    tableRow: {
      flexDirection: 'row',
      borderBottom: '1px solid #E5E7EB',
      padding: 12,
    },
    tableCell: {
      flex: 1,
      fontSize: 10,
    },
    tableCellRight: {
      flex: 1,
      fontSize: 10,
      textAlign: 'right',
    },
    totalSection: {
      marginTop: 30,
      paddingTop: 20,
      borderTop: '2px solid #E5E7EB',
    },
    totalRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 8,
      paddingHorizontal: 0,
    },
    grandTotal: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#3B82F6',
      paddingTop: 10,
      borderTop: '1px solid #E5E7EB',
      marginTop: 10,
    },
    footer: {
      position: 'absolute',
      bottom: 40,
      left: 40,
      right: 40,
      fontSize: 9,
      color: '#9CA3AF',
      paddingTop: 20,
      borderTop: '1px solid #E5E7EB',
      textAlign: 'center',
    },
  }),

  // 2. 클래식 & 전문적 스타일
  classic: StyleSheet.create({
    page: {
      fontFamily: 'Nanum Gothic',
      fontSize: 10,
      padding: 30,
      backgroundColor: '#FFFFFF',
    },
    header: {
      marginBottom: 20,
      borderBottom: '3px double #000',
      paddingBottom: 15,
    },
    title: {
      fontFamily: 'Nanum Gothic Bold',
      fontSize: 28,
      fontWeight: 'bold',
      marginBottom: 10,
      textAlign: 'center',
      textTransform: 'uppercase',
      letterSpacing: 3,
    },
    companyInfo: {
      fontSize: 9,
      marginBottom: 5,
      color: '#333',
      textAlign: 'center',
    },
    section: {
      marginBottom: 20,
    },
    sectionTitle: {
      fontFamily: 'Nanum Gothic Bold',
      fontSize: 12,
      fontWeight: 'bold',
      marginBottom: 10,
      backgroundColor: '#000',
      color: '#FFF',
      padding: 8,
    },
    infoRow: {
      flexDirection: 'row',
      marginBottom: 6,
      borderBottom: '1px dotted #ccc',
      paddingBottom: 4,
    },
    infoLabel: {
      width: 100,
      fontFamily: 'Nanum Gothic Bold',
      fontWeight: 'bold',
    },
    infoValue: {
      flex: 1,
    },
    table: {
      marginTop: 10,
      border: '1px solid #000',
    },
    tableHeader: {
      flexDirection: 'row',
      backgroundColor: '#333',
      color: '#fff',
      padding: 10,
    },
    tableRow: {
      flexDirection: 'row',
      borderBottom: '1px solid #000',
      padding: 8,
    },
    tableCell: {
      flex: 1,
      fontSize: 9,
    },
    tableCellRight: {
      flex: 1,
      fontSize: 9,
      textAlign: 'right',
    },
    totalSection: {
      marginTop: 20,
      borderTop: '3px double #000',
      paddingTop: 15,
    },
    totalRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 5,
      paddingHorizontal: 20,
    },
    grandTotal: {
      fontFamily: 'Nanum Gothic Bold',
      fontSize: 16,
      fontWeight: 'bold',
      color: '#000',
      borderTop: '1px solid #000',
      borderBottom: '3px double #000',
      paddingVertical: 8,
    },
    footer: {
      position: 'absolute',
      bottom: 30,
      left: 30,
      right: 30,
      fontSize: 8,
      color: '#666',
      borderTop: '1px solid #000',
      paddingTop: 10,
      textAlign: 'center',
    },
  }),

  // 3. 컬러풀 & 창의적 스타일
  colorful: StyleSheet.create({
    page: {
      fontFamily: 'Nanum Gothic',
      fontSize: 10,
      padding: 35,
      backgroundColor: '#FAFAFA',
    },
    header: {
      marginBottom: 25,
      backgroundColor: '#6366F1',
      padding: 25,
      borderRadius: 8,
      color: '#FFFFFF',
    },
    title: {
      fontFamily: 'Nanum Gothic Bold',
      fontSize: 30,
      fontWeight: 'bold',
      marginBottom: 10,
      color: '#FFFFFF',
    },
    companyInfo: {
      fontSize: 10,
      marginBottom: 4,
      color: '#E0E7FF',
    },
    section: {
      marginBottom: 20,
      backgroundColor: '#FFFFFF',
      padding: 20,
      borderRadius: 8,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
    },
    sectionTitle: {
      fontFamily: 'Nanum Gothic Bold',
      fontSize: 14,
      fontWeight: 'bold',
      marginBottom: 15,
      color: '#6366F1',
      paddingBottom: 8,
      borderBottom: '2px solid #E0E7FF',
    },
    infoRow: {
      flexDirection: 'row',
      marginBottom: 8,
      backgroundColor: '#F9FAFB',
      padding: 8,
      borderRadius: 4,
    },
    infoLabel: {
      width: 110,
      fontFamily: 'Nanum Gothic Bold',
      color: '#6366F1',
    },
    infoValue: {
      flex: 1,
      color: '#1F2937',
    },
    table: {
      marginTop: 15,
      borderRadius: 8,
      overflow: 'hidden',
    },
    tableHeader: {
      flexDirection: 'row',
      backgroundColor: '#6366F1',
      color: '#FFFFFF',
      padding: 12,
    },
    tableRow: {
      flexDirection: 'row',
      backgroundColor: '#FFFFFF',
      borderBottom: '1px solid #E5E7EB',
      padding: 10,
    },
    tableCell: {
      flex: 1,
      fontSize: 9,
    },
    tableCellRight: {
      flex: 1,
      fontSize: 9,
      textAlign: 'right',
    },
    totalSection: {
      marginTop: 25,
      backgroundColor: '#EEF2FF',
      padding: 20,
      borderRadius: 8,
    },
    totalRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 8,
    },
    grandTotal: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#6366F1',
      paddingTop: 12,
      borderTop: '2px solid #6366F1',
    },
    footer: {
      marginTop: 30,
      fontSize: 9,
      color: '#6B7280',
      textAlign: 'center',
      backgroundColor: '#F3F4F6',
      padding: 15,
      borderRadius: 8,
    },
  }),

  // 4. 비즈니스 & 공식적 스타일
  business: StyleSheet.create({
    page: {
      fontFamily: 'Nanum Gothic',
      fontSize: 10,
      padding: 40,
      backgroundColor: '#FFFFFF',
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 30,
      paddingBottom: 20,
      borderBottom: '2px solid #1E40AF',
    },
    headerLeft: {
      flex: 1,
    },
    headerRight: {
      textAlign: 'right',
    },
    title: {
      fontFamily: 'Nanum Gothic Bold',
      fontSize: 24,
      fontWeight: 'bold',
      marginBottom: 5,
      color: '#1E40AF',
    },
    subtitle: {
      fontSize: 12,
      color: '#64748B',
      marginBottom: 10,
    },
    companyInfo: {
      fontSize: 9,
      marginBottom: 3,
      color: '#475569',
    },
    section: {
      marginBottom: 25,
    },
    sectionTitle: {
      fontFamily: 'Nanum Gothic Bold',
      fontSize: 12,
      fontWeight: 'bold',
      marginBottom: 12,
      color: '#1E40AF',
      textTransform: 'uppercase',
      letterSpacing: 1,
    },
    infoRow: {
      flexDirection: 'row',
      marginBottom: 6,
      paddingVertical: 3,
    },
    infoLabel: {
      width: 100,
      fontSize: 9,
      color: '#64748B',
      textTransform: 'uppercase',
      fontSize: 8,
    },
    infoValue: {
      flex: 1,
      fontSize: 10,
      color: '#1E293B',
    },
    table: {
      marginTop: 10,
    },
    tableHeader: {
      flexDirection: 'row',
      backgroundColor: '#1E40AF',
      color: '#FFFFFF',
      padding: 10,
    },
    tableRow: {
      flexDirection: 'row',
      borderBottom: '1px solid #E2E8F0',
      padding: 10,
      backgroundColor: '#FFFFFF',
    },
    tableRowAlt: {
      backgroundColor: '#F8FAFC',
    },
    tableCell: {
      flex: 1,
      fontSize: 9,
    },
    tableCellRight: {
      flex: 1,
      fontSize: 9,
      textAlign: 'right',
    },
    totalSection: {
      marginTop: 30,
      backgroundColor: '#F1F5F9',
      padding: 20,
    },
    totalRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 8,
      paddingHorizontal: 10,
    },
    grandTotal: {
      fontSize: 16,
      fontWeight: 'bold',
      color: '#1E40AF',
      backgroundColor: '#DBEAFE',
      padding: 12,
      marginTop: 10,
    },
    footer: {
      position: 'absolute',
      bottom: 40,
      left: 40,
      right: 40,
      fontSize: 8,
      color: '#64748B',
      paddingTop: 15,
      borderTop: '2px solid #E2E8F0',
    },
  }),
};